version: "3"
services:
    app:
        container_name: full_app
        build: .
        ports:
            - 8088:8088
        restart: on-failure
        volumes:
            - api:/usr/src/app/
        networks:
            - fullstack

volumes:
    api:

networks:
    fullstack:
        driver: bridge
